In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("./data/emails.csv") 
df.head()

,id,sender,subject,date,body
0,1a0ee7f368c3a9d5,Google <no-reply@accounts.google.com>,Security alert,"Tue, 29 Sep 2026 18:48:28 GMT",[image: Google]\r\nYou allowed Gmail ML Classi...
1,1a0ee1b30aeb0787,LinkedIn <messages-noreply@linkedin.com>,Data Scientist: Harnham and Datatech Analytics...,"Tue, 29 Sep 2026 16:59:14 +0000 (UTC)",----------------------------------------\r\nHi...
2,1a0ee09e68b497a7,Standard Life <Emails@service.standardlife.co.uk>,Six ways to make more of your pension in 2026,"Tue, 29 Sep 2026 09:52:46 -0600","To view this email as a web page, go to the li..."
3,1a0edf319a0f17e0,no-reply@employmenthero.com,Your timesheets have been updated,"Tue, 29 Sep 2026 16:15:23 +0000 (UTC)",NaN
4,1a0ed5f442b7a816,Stream <hello@comms.stream.co>,Check out your latest offers from Stream Rewar...,"Tue, 29 Sep 2026 13:33:58 +0000",Don't miss exclusive discounts and the chance ...

In [4]:
df.isna().sum()

id          0
sender      0
subject     1
date        0
body       17
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       100 non-null    object
 1   sender   100 non-null    object
 2   subject  99 non-null     object
 3   date     100 non-null    object
 4   body     83 non-null     object
dtypes: object(5)
memory usage: 4.0+ KB

In [18]:
# missing bodies
df[df["body"].isna()][["sender", "subject", "body"]]

,sender,subject,body
3,no-reply@employmenthero.com,Your timesheets have been updated,NaN
9,Anthropic Education <academy-support@anthropic...,Complete your signup,NaN
13,Uber <uber@uber.com>,Take the work out of going to work,NaN
15,Revolut <no-reply@revolut.com>,You sent £7.99 to Clement Appeadu 💸,NaN
16,no-reply@employmenthero.com,Your timesheets have been updated,NaN
24,Uber <uber@uber.com>,Stay prepared with your trips and get 20% off,NaN
28,Uber <uber@uber.com>,Get £5 off your first train ticket today,NaN
51,no-reply@employmenthero.com,Your timesheets have been updated,NaN
57,no-reply@employmenthero.com,Acknowledgement confirmation for employment do...,NaN
61,no-reply@employmenthero.com,Your timesheets have been updated,NaN
64,no-reply@employmenthero.com,Employment documents have been added to your a...,NaN
81,no-reply@employmenthero.com,Your timesheets have been updated,NaN
89,Hotelcare <recruitment-support@hotelcare.co.uk>,Important request from Hotelcare,NaN
91,Uber <uber@uber.com>,"Clement, Grab £5 off your first in-app train t...",NaN
93,no-reply@employmenthero.com,Your timesheets have been updated,NaN
94,Uber <uber@uber.com>,50% off eats unlocked,NaN
97,no-reply@employmenthero.com,Acknowledgement confirmation for employment do...,NaN

In [ ]:
# visual inspection reveals that these are empty because the body contains images which have the message 
# of the email.

In [ ]:
# no subject
df[df["subject"].isna()][["sender", "subject", "body"]]

,sender,subject,body
83,CLEMENT APPEADU <appeaduclement@gmail.com>,NaN,# RiskLens foundation and modeling plan\r\n\r\...

In [ ]:
# for this is subject was actually not given

In [20]:
# understand senders
df["sender"].value_counts().head(20)

sender
LinkedIn Job Alerts <jobalerts-noreply@linkedin.com>                  13
no-reply@employmenthero.com                                            9
LinkedIn <notifications-noreply@linkedin.com>                          8
LinkedIn <messages-noreply@linkedin.com>                               7
National Express <nx-reply@nationalexpress.com>                        6
Uber <uber@uber.com>                                                   5
LinkedIn <updates-noreply@linkedin.com>                                4
Google <no-reply@accounts.google.com>                                  4
Codecademy <learn@itr.mail.codecademy.com>                             4
LinkedIn <jobs-noreply@linkedin.com>                                   4
Stream <hello@comms.stream.co>                                         4
GitHub <noreply@github.com>                                            3
OpenAI <noreply@email.openai.com>                                      2
Debenhams Outlet <news@email.debenhamsoutlet.com>                      2
Virgin Atlantic Flying Club <flyingclub@emails.virginatlantic.com>     2
Anthropic Education <academy-support@anthropic.com>                    2
Lloyds Bank <info@emails.lloydsbank.com>                               2
Standard Life <Emails@service.standardlife.co.uk>                      1
Lloyds Bank Investing <info@emails.lloydsbank.com>                     1
Revolut <no-reply@revolut.com>                                         1
Name: count, dtype: int64

In [ ]:
# understand subjects
df["subject"].head(20)

0                                        Security alert
1     Data Scientist: Harnham and Datatech Analytics...
2         Six ways to make more of your pension in 2026
3                     Your timesheets have been updated
4     Check out your latest offers from Stream Rewar...
5     🚨 Clement, Outlet                             ...
6                          Why wait to invest, Clement?
7         Senior Human Resources Officer at Talent Ogin
8     Your registration for Building with the Claude...
9                                  Complete your signup
10    Emmanuela Amadi - Project Manager reacted to t...
11                            You have 1 new invitation
12       With fares from £7.50*, get away this autumn 🍂
13                   Take the work out of going to work
14                SALE EXTENDED: Back to school 50% off
15                  You sent £7.99 to Clement Appeadu 💸
16                    Your timesheets have been updated
17                         Data Scientist at Data Idols
18                       🎁10% off is waiting for you...
19    💸 Clement, New In: At Least 60% Off           ...
Name: subject, dtype: object